### ISSUE TITLE
livox mid 360

### ISSUE THREAD

**Issue by slamer2024** [Kin-Zhang/simple_ndt_slam#11]
您好，我想使用在livox mid 360 上，但是map的方向以及准确性好像有点问题，这个因为扫描方法不一样吗？

**Comment by slamer2024** [comment]
谢谢回复，这个是我rosbag [链接：](https://drive.google.com/file/d/1EMUWpbST57VEfJ92CCzQzHH5iNH0PkHI/view?usp=drive_link)
我是在ubuntu20.04 ros noetic上运行的。没有使用/livox/imu (用了更奇怪）。一下我附上hdl_slam结果，虽然在尾部有些drift，但和google map上比较，还算准确。
![Screenshot from 2024-04-15 14-27-50](https://github.com/Kin-Zhang/simple_ndt_slam/assets/167066146/f13eac3c-da5a-4345-9491-c402729ba30f)

**Comment by Kin-Zhang** [comment]
![image](https://github.com/Kin-Zhang/simple_ndt_slam/assets/35365764/cd77b08e-5a88-4dda-8dae-78a36cb3d87f)

![image](https://github.com/Kin-Zhang/simple_ndt_slam/assets/35365764/a6cebdc2-cb12-4dac-83b6-f1c278c8523f)

我大致看了一下 好像问题出在后半部分，我随手重构的这个 确实没试过较大的场景（我当时是写给室内机器人用来着）
- IMU是因为 外参的原因，我没写那部分
- 关于后半部分飘的原因 可能是因为ndt的voxel size设置的需要进行调整，这是我运行的config.yaml 供你参考 【图1，图2 是仅定位使用的话：save_frame_point: 10】

如果是要运行有IMU的算法，我建议可以试一下[fast-lio2](https://github.com/hku-mars/FAST_LIO) 比较好，
我这个当时就徒个快和简单，最近我有在考虑要不要深度改进一下 但是时间原因可能悬... 


```yaml
lidar_frame: "livox_frame"
lidar_topic: "livox/lidar"
odom_topic : ""
imu_topic  : ""

# output things ================ >
odom_lidar_topic : "/repub_points"  # sensor_msgs::PointCloud2
output_odom_topic: "/auto_odom"   # nav_msgs::Odometry

debug_print: true  # will republish point with current timestamp
use_odom   : false
use_imu    : false

imu_upside_down: false  # whether inverse the imu axis
odom_inverse: true
incremental_voxel_update: true

# setting -1 mean it will output the whole ndt map ===> FOR THE WHOLE MAP
# setting 10 mean 10*frame_point_num will be saved ===> FOR FAST LOC
save_frame_point: -1

baselink2LiDAR: [0, 0, 0, 0, 1.0, 0] # x,y,z, roll, pitch, yaw

# parameter's for ndt =========================== >
# Cell Size while mapping using ND (meters) (default 1.0)
resolution: 0.3

# Increment value between iterations while matching (default 0.1)
step_size: 0.1

# Value to decide convergence between iterations (meters) (default 0.01)
trans_epsilon: 0.01

# Maximum number of iterations before stopping matching (default 30)
max_iterations: 30

# Voxel Grid Size of the input scan (downsampling) (default 1.0)
leaf_size: 0.3

# Ignore points closer than this value (meters) (default 5.0)
min_scan_range: 0.1

# Ignore points far than this value (meters) (default 200.0)
max_scan_range: 20.0

# Minimum distance between points to be added to the final map (default 1.0)
min_add_scan_shift: 0.3
```
